Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Models;
using Ecommerce.Data.Services;

namespace Ecommerce.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorsService _authorsService;

        public AuthorController(IAuthorsService authorsService)
        {
            _authorsService = authorsService;
        }

        // GET: Author
        public async Task<IActionResult> Index()
        {
            var authors = await _authorsService.GetAllAsync();
              return authors != null ? 
                          View(await _authorsService.GetAllAsync()) :
                          Problem("Entity set 'AppDbContext.Authors'  is null.");
        }

        // GET: Author/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || await _authorsService.GetByIdAsync((int)id) == null)
            {
                return View("NotFound");
            }

            var author = await _authorsService.GetByIdAsync((int)id);
            if (author == null)
            {
                return View("NotFound");
            }

            return View(author);
        }

        // GET: Author/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FullName,Bio,ImageURL")] Author author)
        {
            if (ModelState.IsValid)
            {
                await _authorsService.AddAsync(author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Author/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _authorsService.GetAllAsync() == null)
            {
                return View("NotFound");

            }

            var author = await _authorsService.GetByIdAsync((int)id);
            if (author == null)
            {
                return View("NotFound");
            }
            return View(author);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FullName,Bio,ImageURL")] Author author)
        {
            if (id != author.ID)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _authorsService.UpdateAsync(id,author);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await AuthorExistsAsync(author.ID))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Author/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _authorsService.GetAllAsync()==null)
            {
                return View("NotFound");
            }

            var author = await _authorsService.GetByIdAsync((int)id);
            if (author == null)
            {
                return View("NotFound");
            }

            return View(author);
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _authorsService.GetAllAsync() == null)
            {
                return Problem("Entity set 'AppDbContext.Authors'  is null.");
            }
            await _authorsService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> AuthorExistsAsync(int id)
        {
            var author = await _authorsService.GetByIdAsync(id);
            return author!=null ? true : false;
        }
    }
}

Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Models;
using Ecommerce.Data.Services;

namespace Ecommerce.Controllers
{
    public class BookController : Controller
    {
        private readonly IBooksService _booksService;

        public BookController(IBooksService booksService)
        {
            _booksService = booksService;
        }

        // GET: Book
        public async Task<IActionResult> Index()
        {
            var books = await _booksService.GetAllAsync();
              return books != null ? 
                          View(await _booksService.GetAllAsync()) :
                          Problem("Entity set 'AppDbContext.Books'  is null.");
        }

        // GET: Book/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || await _booksService.GetAllAsync() == null)
            {
                return View("NotFound");
            }

            var book = await _booksService.GetByIdAsync((int)id);
            if (book == null)
            {
                return View("NotFound");
            }

            return View(book);
        }

        // GET: Book/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,Price,ImageURL,ReleaseDate,PagesNumber,BookCategory")] Book book)
        {
            if (ModelState.IsValid)
            {
                await _booksService.AddAsync(book);
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Book/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _booksService.GetAllAsync() == null)
            {
                return View("NotFound");
            }

            var book = await _booksService.GetByIdAsync((int)id);
            if (book == null)
            {
                return View("NotFound");
            }
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description,Price,ImageURL,ReleaseDate,PagesNumber,BookCategory")] Book book)
        {
            if (id != book.ID)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _booksService.UpdateAsync(id,book);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await BookExistsAsync(book.ID))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Book/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _booksService.GetAllAsync() == null)
            {
                return View("NotFound");
            }

            var book = await _booksService.GetByIdAsync((int)id);
            if (book == null)
            {
                return View("NotFound");
            }

            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _booksService.GetAllAsync() == null)
            {
                return Problem("Entity set 'AppDbContext.Books'  is null.");
            }
            await _booksService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> BookExistsAsync(int id)
        {
            var book = await _booksService.GetByIdAsync(id);
            return book != null;
        }
    }
}

Controllers/OrdersController.cs
using Ecommerce.Data.Cart;
using Ecommerce.Data.Services;
using Ecommerce.Data.ViewModels;
using Ecommerce.Data.Static;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Ecommerce.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IBooksService _booksService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IBooksService booksService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _booksService = booksService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _booksService.GetByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _booksService.GetByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

Controllers/PublisherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Models;
using Ecommerce.Data.Services;

namespace Ecommerce.Controllers
{
    public class  PublisherController : Controller
    {
        private readonly IPublishersService _publishersService;

        public PublisherController(IPublishersService publishersService)
        {
            _publishersService = publishersService;
        }

        // GET: Author
        public async Task<IActionResult> Index()
        {
            var authors = await _publishersService.GetAllAsync();
            return authors != null ?
                        View(await _publishersService.GetAllAsync()) :
                        Problem("Entity set 'AppDbContext.Authors'  is null.");
        }

        // GET: Author/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || await _publishersService.GetByIdAsync((int)id) == null)
            {
                return View("NotFound"); ;
            }

            var publisher = await _publishersService.GetByIdAsync((int)id);
            if (publisher == null)
            {
                return View("NotFound");
            }

            return View(publisher);
        }

        // GET: Author/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Bio,ImageURL")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                await _publishersService.AddAsync(publisher);
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Author/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _publishersService.GetAllAsync() == null)
            {
                return View("NotFound");
            }

            var publisher = await _publishersService.GetByIdAsync((int)id);
            if (publisher == null)
            {
                return View("NotFound");
            }
            return View(publisher);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Bio,ImageURL")] Publisher publisher)
        {
            if (id != publisher.ID)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _publishersService.UpdateAsync(id,publisher);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await AuthorExistsAsync(publisher.ID))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Author/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _publishersService.GetAllAsync() == null)
            {
                return View("NotFound");
            }

            var author = await _publishersService.GetByIdAsync((int)id);
            if (author == null)
            {
                return View("NotFound");
            }

            return View(author);
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _publishersService.GetAllAsync() == null)
            {
                return Problem("Entity set 'AppDbContext.Authors'  is null.");
            }
            await _publishersService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> AuthorExistsAsync(int id)
        {
            var publisher = await _publishersService.GetByIdAsync(id);
            return publisher != null ? true : false;
        }
    }
}

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">The page you're looking for is not found</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Book" asp-action="Index">Home Page</a>
    </div>
</div>

Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-bs-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Author" asp-action="Index"><i class="bi bi-pencil"></i> Authors</a>
                                    <a class="dropdown-item" asp-controller="Publisher" asp-action="Index"><i class="bi bi-newspaper"></i> Publishers</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <form class="form-inline my-2 my-lg-0 d-flex" asp-controller="Book" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a book..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ecommerce
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>